name: "docker"
on:
  workflow_dispatch:
    inputs:

  push:
    branches:
      - master
jobs:
  cancel:
    name: Cancel Previous Runs
    runs-on: ubuntu-latest
    steps:
      - name: cancel running workflows
        uses: GongT/cancel-previous-workflows@6dd7af8389c9434cc893fd33b58609e73db49fbe
        env:
          DELETE: "yes"
          GITHUB_TOKEN: ${{ matrix.secrets.GITHUB_TOKEN }}
  build:
    name: "build docker images"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: 
          - edge
          - latest
          - minimal
          - glibc
    steps:
      - name: Check Out
        uses: actions/checkout@v3
        
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: gongt
          password: ${{ secrets.SECRET_HUB }}
        
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ghcr.io/gongt/init

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: docker.io/gongt/alpine-init

      - name: Build and push docker.io
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: docker.io/gongt/alpine-init:${{ matrix.tag }}
          

      - name: Build and push ghcr.io
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/gongt/init:${{ matrix.tag }}
          
